spring:
  datasource:
    url: jdbc:mysql://129.204.203.171:3306/skill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 129.204.203.171
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 0
  application:
    name: login
    
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  
    